### PR TITLE
JSX props map to object properties

### LINKED ISSUE #46: Property-names get lower-cased?
It looks like property-names are getting lower-cased?

For example, `<div className="red">` gets rendered as `<div classname="red">`, which doesn't work, since the property-names are case-sensitive:

image

I've been looking through the code, and can't figure out where or how this happens.

If I take the same example and import `h` and `render` from e.g. `preact`, it works fine, so I don't think it's CodeSandbox mangling the code or something? 🤔

I only see one call to `toLowerCase()` in the code, and it applies only to event-handlers.

Any ideas?

### PR DESCRIPTION
**Pull request by mindplay-dk**
JSX props map to object properties by default and falls back to attributes - except for SVG elements, which always use attributes.

Closes #46 

I will add some inline notes to the PR in a moment.

### CODE REVIEW

File: demo/svg.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ function App () {
   const [flag, setFlag] = useState(true)
   return (
     <div style={flag? { color: 'red' } : { backgroundColor: 'black' }}>
-      <svg xmlns='http://www.w3.org/2000/svg' version='1.1'>
```
Comment (mindplay-dk) [inline demo/svg.js]: Removed, since `updateElement()` would otherwise attempt to set these!

File: src/dom.js [hunk 2]
```diff
@@ -19,11 +21,7 @@ function updateProperty (dom, name, value, newValue) {
 export function updateElement (dom, props, newProps) {
   Object.keys(newProps)
     .filter(isNew(props, newProps))
-    .forEach(key => {
-      key === 'value' || key === 'nodeValue'
-        ? (dom[key] = newProps[key])
-        : updateProperty(dom, key, props[key], newProps[key])
-    })
```
Comment (mindplay-dk) [inline src/dom.js]: No special handling of `value` and `nodeValue` required anymore, as these are properties - they will be detected and handled by the `name in dom` test above.

**Comment by mindplay-dk** [comment]
Since I don't know how to get the tests working yet, there are no tests for this yet.

You can see working examples [here](https://codesandbox.io/s/counters-in-fre-uxuic), including both `class` and `className` working now, `readOnly` property working with a literal `true`, and SVG element with attributes rather than properties updating correctly.

**Comment by 132yse** [comment]
Hey, I'm back.
I see that use cases work great, so merge this request first~

Thank you very much.

**Comment by 132yse** [comment]
I don't quite understand why it can support className. How does it work??

File: demo/svg.js (hunk 1 above)
Comment (132yse) [reply demo/svg.js]: That's OK.

File: src/dom.js (hunk 2 above)
Comment (132yse) [reply src/dom.js]: I can reduce code sizes here 😄

**Comment by mindplay-dk** [comment]
> I don't quite understand why it can support className. How does it work??

The test for `name in dom` will detect it and set it - for example:

    console.log("className" in (document.createElement("div"))); // => true

This will cause the property to be set.

As opposed to:

    console.log("class" in (document.createElement("div"))); // => false

This will continue on to `setAttribute()` as before.
